"""The Open Universe save: what goes in comes back out.

Drives the REAL save and load functions (universe_core/universe_helpers.py, loaded
through MAST's own `import` the way a mission loads them) against the mock, on saves
that were GENERATED by playing sandbox copies headless:

  tests/saves/v1_default.yaml      the Default universe, three jumps in, seventeen jobs
                                   in hand, standing with six sides
  tests/saves/v1_story.yaml        The Fading Signal: one step done, one open, one hidden
  tests/saves/v1_ou_template.yaml  a mission made from the `ou` template (the author
                                   course's Kestrel Verge), two evenings in

All three are version 1, written before ships had a stable id. They are fixtures: they
are never rewritten, and every test works on a copy in a temp folder.

Run:  python -m unittest tests.test_save_roundtrip     (from the OpenUniverse folder)
"""
import copy
import os
import shutil
import sys
import tempfile
import unittest

_HERE = os.path.dirname(os.path.abspath(__file__))
OU_CORE = os.path.abspath(os.path.join(_HERE, "..", "universe_core"))
FIXTURES = os.path.join(_HERE, "saves")
SBS = os.path.abspath(os.path.join(_HERE, "..", "..", "sbs_utils"))
sys.path.insert(0, SBS)

from sbs_utils.fs import test_set_exe_dir
test_set_exe_dir()

import cosmos_dev.mock.sbs as mock_sbs
sys.modules.setdefault("sbs", mock_sbs)

import sbs_utils.fs as fs
import sbs_utils.mast_sbs.story_nodes  # noqa: F401
from sbs_utils.agent import Agent, clear_shared
from sbs_utils.helpers import Context, FakeEvent, FrameContext
from sbs_utils.mast.mast_globals import MastGlobals
from sbs_utils.mast.maststory import MastStory
from sbs_utils.procedural.inventory import get_inventory_value, set_inventory_value
from sbs_utils.procedural.quest import quest_get, quest_get_state, quest_set_key
from sbs_utils.procedural.sides import side_ensure, to_side_id
from sbs_utils.procedural.spawn import player_spawn
from sbs_utils.spaceobject import SpaceObject

FIXTURE_NAMES = ("v1_default.yaml", "v1_story.yaml", "v1_ou_template.yaml")


def _read_bytes(path):
    with open(path, "rb") as f:
        return f.read()


def players_by_name(data):
    """The ship records of a save, keyed by the ship's NAME - whichever version wrote
    it. Version 1 keyed `players` by name; version 2 keys it by a stable id and holds
    the name inside the record."""
    out = {}
    for key, rec in (data.get("players") or {}).items():
        out[rec.get("name", key) if isinstance(rec, dict) else key] = rec
    return out


class SaveHarness(unittest.TestCase):
    """The mission's Python, loaded once per class into its own namespace, with the
    saves folder pointed at a temp directory."""

    @classmethod
    def setUpClass(cls):
        cls.root = tempfile.mkdtemp(prefix="ou_save_test_")
        cls.mission = os.path.join(cls.root, "mission")
        os.makedirs(cls.mission)
        cls.old_script_dir = fs.script_dir
        # common_data is the mission folder's SIBLING, so this is what moves the saves.
        fs.script_dir = cls.mission
        cls.old_globals = dict(MastGlobals.globals)
        story = MastStory()
        story.basedir = OU_CORE
        cls.errors = story.compile("import universe_helpers.py\n", "save_harness", story)
        cls.story = story

    @classmethod
    def tearDownClass(cls):
        MastGlobals.globals.clear()
        MastGlobals.globals.update(cls.old_globals)
        fs.script_dir = cls.old_script_dir
        shutil.rmtree(cls.root, ignore_errors=True)

    def setUp(self):
        self.assertEqual(self.errors, [])
        shutil.rmtree(os.path.join(self.root, "common_data"), ignore_errors=True)
        self.launch()

    def launch(self):
        """A fresh process as far as the game can tell: a new sim, no ships, no shared
        state - and whatever is in the saves folder still there. A test that plays two
        evenings calls this between them."""
        fs.script_dir = self.mission
        mock_sbs.create_new_sim()
        mock_sbs.resume_sim()
        SpaceObject.clear()
        clear_shared()
        FrameContext.context = Context(mock_sbs.sim, mock_sbs, FakeEvent(0, "test"))
        FrameContext.page = None
        Agent.SHARED.set_inventory_value("sim", mock_sbs.sim)
        reset = MastGlobals.globals.get("universe_save_reset")
        if reset is not None:
            reset()
        self.fn("universe_set_active_save")("Round Trip", 1)
        self.path = self.fn("universe_save_path")()
        # A test that resolves the real saves folder is a defect, so say so before
        # anything is written.
        inside = os.path.normcase(os.path.abspath(self.path)).startswith(
            os.path.normcase(os.path.abspath(self.root)))
        self.assertTrue(inside, "the save path left the temp folder: " + self.path)

    def tearDown(self):
        FrameContext.context = None

    def fn(self, name):
        return MastGlobals.globals[name]

    def module_globals(self):
        """universe_helpers.py's own namespace - where its private names live."""
        return self.fn("universe_save_players").__globals__

    def install(self, fixture):
        """Put a copy of a fixture where the active save is read from."""
        os.makedirs(os.path.dirname(self.path), exist_ok=True)
        shutil.copyfile(os.path.join(FIXTURES, fixture), self.path)
        return _read_bytes(self.path)

    def write_save(self, text):
        os.makedirs(os.path.dirname(self.path), exist_ok=True)
        with open(self.path, "w", encoding="utf-8", newline="\n") as f:
            f.write(text)
        return _read_bytes(self.path)

    def ship(self, name, side="tsn"):
        side_ensure(side)
        return player_spawn(0, 0, 0, name, side, "tsn_light_cruiser").py_object

    def files(self):
        folder = os.path.dirname(self.path)
        return sorted(os.listdir(folder)) if os.path.isdir(folder) else []

    def begin(self, mode):
        """What universe_map_begin does with the save before anything is spawned."""
        return self.fn("universe_save_begin")(mode)

    def finish(self, mode, saved, seed=7):
        """...and what it does once the ships exist."""
        if saved is None:
            self.fn("universe_save")(seed, 0, 0, {})
        else:
            cur = saved.get("current_system", [0, 0])
            self.fn("universe_save")(saved.get("universe_seed", 1), cur[0], cur[1],
                                     saved.get("systems", {}))
        self.fn("universe_load_players")(mode == "Continue")
        self.fn("universe_save_ready")()
        self.fn("universe_save_players")()


class RoundTrip(SaveHarness):
    """Load, restore onto ships, save, load again: nothing is lost and nothing moves."""

    def round_trip(self, fixture):
        self.install(fixture)
        before = copy.deepcopy(self.fn("universe_load")())
        self.assertIsNotNone(before)
        ships = {name: self.ship(name) for name in players_by_name(before)}
        saved = self.begin("Continue")
        self.assertIsNotNone(saved)
        self.finish("Continue", saved)
        after = self.fn("universe_load")()
        return before, after, ships

    def assert_same_campaign(self, before, after):
        for key in ("universe_seed", "current_system", "systems", "side_credits",
                    "side_admiralty", "shared_quests"):
            self.assertEqual(after.get(key), before.get(key), key)
        was, now = players_by_name(before), players_by_name(after)
        self.assertEqual(sorted(now), sorted(was))
        for name, rec in was.items():
            for field in ("items", "installs", "quests", "reputation"):
                self.assertEqual(now[name].get(field), rec.get(field), f"{name}.{field}")

    def test_the_default_universe_comes_back_whole(self):
        before, after, ships = self.round_trip("v1_default.yaml")
        self.assert_same_campaign(before, after)
        artemis = ships["Artemis"]
        # Not only in the file: on the ship.
        self.assertEqual(quest_get_state(artemis.id, "cargo_0_0"), 1)
        self.assertEqual(quest_get_state(artemis.id, "side_iron_patrol"), 1)
        self.assertEqual(get_inventory_value(artemis.id, "reputation")["iron"]["nerve"], 25)
        self.assertEqual(get_inventory_value(to_side_id("tsn"), "credits"), 500)
        self.assertEqual(after["current_system"], [2, 1])

    def test_a_story_keeps_its_done_open_and_hidden_steps(self):
        before, after, _ = self.round_trip("v1_story.yaml")
        self.assert_same_campaign(before, after)
        states = {key: quest_get_state(Agent.SHARED_ID, key)
                  for key in ("signal_1", "signal_2", "signal_3")}
        self.assertEqual(states, {"signal_1": 99, "signal_2": 1, "signal_3": 2})

    def test_an_ou_template_mission_comes_back_whole(self):
        before, after, ships = self.round_trip("v1_ou_template.yaml")
        self.assert_same_campaign(before, after)
        self.assertEqual(quest_get_state(Agent.SHARED_ID, "s02_home"), 99)
        self.assertEqual(quest_get_state(Agent.SHARED_ID, "s03_go"), 1)
        self.assertEqual(quest_get_state(Agent.SHARED_ID, "act1_close"), 2)
        self.assertIsNotNone(quest_get(Agent.SHARED_ID, "waypoints/wp_2_2"))
        self.assertEqual(get_inventory_value(ships["Artemis"].id, "reputation"),
                         {"hollin": {"honesty": 40, "generosity": 40}})
        self.assertEqual(get_inventory_value(to_side_id("tsn"), "credits"), 1150)

    def test_a_second_round_trip_changes_nothing(self):
        self.install("v1_default.yaml")
        self.ship("Artemis")
        self.finish("Continue", self.begin("Continue"))
        once = _read_bytes(self.path)
        self.fn("universe_save_players")()
        self.assertEqual(_read_bytes(self.path), once)


def _boom(data):
    raise ValueError("migration step 1 is broken")


class Safety(SaveHarness):
    """A save that will not load is never written over, and a New Game is a new game."""

    def break_the_ladder(self):
        g = self.module_globals()
        old = g["_MIGRATIONS"]
        g["_MIGRATIONS"] = {1: _boom}
        self.addCleanup(g.__setitem__, "_MIGRATIONS", old)

    def play_an_evening(self, mode, saved):
        """Everything that writes the save during play."""
        self.ship("Artemis")
        self.finish(mode, saved)
        self.fn("universe_save")(7, 3, 3, {"3,3": {"visited": True}})
        self.fn("universe_save_diplomacy")({"tsn|iron": 2})
        self.fn("universe_save_request")()
        self.fn("universe_save_flush")()
        self.fn("universe_save_state")({"universe_seed": 1})

    def test_GAP_11_a_save_that_will_not_migrate_is_left_alone_with_a_copy(self):
        original = self.install("v1_default.yaml")
        self.break_the_ladder()
        saved = self.begin("Continue")
        self.assertIsNone(saved, "the evening still plays, as a new game")
        self.play_an_evening("Continue", saved)
        self.assertEqual(_read_bytes(self.path), original)
        self.assertEqual(_read_bytes(self.path + ".v1.bak"), original)
        self.assertEqual(self.files(), ["universe_save_round_trip_1.yaml",
                                        "universe_save_round_trip_1.yaml.v1.bak"])
        why = self.fn("universe_save_blocked")()
        self.assertIn("could not be loaded", why)
        self.assertIn("migration step 1 is broken", why)
        self.assertIn("universe_save_round_trip_1.yaml.v1.bak", why)
        self.assertIn(why, self.fn("universe_save_report")("Continue"))

    def test_GAP_11_an_unreadable_save_is_left_alone_with_a_copy(self):
        original = self.write_save("players: [unclosed\n  nope: : :\n")
        saved = self.begin("Continue")
        self.assertIsNone(saved)
        self.play_an_evening("Continue", saved)
        self.assertEqual(_read_bytes(self.path), original)
        self.assertEqual(_read_bytes(self.path + ".unreadable.bak"), original)
        self.assertIn("unreadable", self.fn("universe_save_blocked")())

    def test_a_save_from_a_newer_build_is_played_and_not_written_over(self):
        original = self.write_save("save_version: 9\nuniverse_seed: 5\ncurrent_system:\n- 4\n- 4\n")
        saved = self.begin("Continue")
        self.assertEqual(saved["universe_seed"], 5)
        self.play_an_evening("Continue", saved)
        self.assertEqual(_read_bytes(self.path), original)
        self.assertIn("newer build", self.fn("universe_save_blocked")())

    def test_a_write_that_meets_a_broken_file_mid_session_stops_too(self):
        # Not through universe_save_begin: the file goes bad while the game is running.
        self.ship("Artemis")
        self.finish("Continue", self.begin("Continue"))
        original = self.write_save("players: [unclosed\n")
        self.fn("universe_save")(7, 1, 1, {})
        self.fn("universe_save_players")()
        self.assertEqual(_read_bytes(self.path), original)
        self.assertEqual(_read_bytes(self.path + ".unreadable.bak"), original)

    def test_continue_with_no_file_starts_one(self):
        self.assertIsNone(self.begin("Continue"))
        self.ship("Artemis")
        self.finish("Continue", None)
        data = self.fn("universe_load")()
        self.assertEqual(data["save_version"], 2)
        self.assertEqual(list(data["players"]), ["artemis"])
        self.assertEqual(self.fn("universe_save_blocked")(), "")

    def test_GAP_12_a_new_game_does_not_inherit_the_old_diplomacy(self):
        original = self.install("v1_default.yaml")
        self.ship("Artemis")
        self.finish("Continue", self.begin("Continue"))
        self.fn("universe_save_diplomacy")({"tsn|iron": 2})
        self.fn("universe_save_state")(dict(self.fn("universe_load")(), state={"relics": {"a": 1}}))
        old_campaign = _read_bytes(self.path)
        self.launch()                                  # the next launch
        self.ship("Artemis")
        saved = self.begin("New Game")
        self.assertIsNone(saved)
        self.finish("New Game", saved)
        data = self.fn("universe_load")()
        self.assertEqual(data.get("diplomacy", {}), {})
        self.assertNotIn("state", data, "a section this build does not know is the old "
                                        "campaign's too")
        self.assertEqual(data["players"]["artemis"]["quests"], {})
        self.assertEqual(data["current_system"], [0, 0])
        # The campaign that was there is one file away, and so is the version-1 original.
        self.assertEqual(_read_bytes(self.path + ".previous.bak"), old_campaign)
        self.assertEqual(_read_bytes(self.path + ".v1.bak"), original)

    def test_a_new_game_over_a_broken_file_keeps_a_copy_and_saves(self):
        original = self.write_save("players: [unclosed\n")
        self.ship("Artemis")
        self.finish("New Game", self.begin("New Game"))
        self.assertEqual(_read_bytes(self.path + ".previous.bak"), original)
        self.assertEqual(self.fn("universe_save_blocked")(), "")
        self.assertEqual(list(self.fn("universe_load")()["players"]), ["artemis"])


class SaveRequest(SaveHarness):
    """Quest changes ask for a save; one write serves a burst; nothing is written while
    the campaign is still loading."""

    def test_nothing_writes_players_until_the_campaign_is_restored(self):
        original = self.install("v1_default.yaml")
        self.ship("Artemis")
        saved = self.begin("Continue")
        # universe_map_begin has reset the session (setUp did) and has not said ready.
        # The ship is spawned and EMPTY; a save now would write that over its jobs.
        self.assertFalse(self.fn("universe_save_players")())
        self.assertFalse(self.fn("universe_save_flush")())
        self.assertEqual(_read_bytes(self.path), original)
        self.assertTrue(self.fn("universe_save_pending")(), "asked for, not forgotten")
        self.finish("Continue", saved)
        self.assertFalse(self.fn("universe_save_pending")())
        jobs = players_by_name(self.fn("universe_load")())["Artemis"]["quests"]
        self.assertEqual(len(jobs), 17)

    def test_a_burst_of_requests_is_one_write(self):
        self.ship("Artemis")
        self.finish("Continue", self.begin("Continue"))
        self.assertFalse(self.fn("universe_save_flush")(), "nothing asked for")
        g = self.module_globals()
        writes = []
        real = g["_universe_write"]
        g["_universe_write"] = lambda change: writes.append(1) or real(change)
        self.addCleanup(g.__setitem__, "_universe_write", real)
        for _ in range(5):
            self.fn("universe_save_request")()
        self.assertTrue(self.fn("universe_save_flush")())
        self.assertFalse(self.fn("universe_save_flush")())
        self.assertEqual(len(writes), 1)

    def test_a_failed_step_reaches_the_file_without_a_jump(self):
        self.install("v1_default.yaml")
        artemis = self.ship("Artemis")
        self.finish("Continue", self.begin("Continue"))
        quest_set_key(artemis.id, "cargo_0_0", "state", 98)
        quest_set_key(Agent.SHARED_ID, "truce_1", "state", 99)
        self.fn("universe_save_request")()
        self.assertTrue(self.fn("universe_save_flush")())
        data = self.fn("universe_load")()
        self.assertEqual(players_by_name(data)["Artemis"]["quests"]["cargo_0_0"]["state"], 98)
        self.assertEqual(data["shared_quests"]["truce_1"]["state"], 99)

    def test_the_routes_that_ask_are_server_routes(self):
        with open(os.path.join(OU_CORE, "universe.mast"), encoding="utf-8") as f:
            text = f.read()
        for name in ("quest_succeeded", "quest_failed_done", "quest_started"):
            start = text.index("//shared/signal/" + name + " if UNIVERSE_ACTIVE")
            end = text.index("\n\n\n", start) if name == "quest_succeeded" else text.index("\n\n", start)
            self.assertIn("universe_save_request()", text[start:end], name)
            self.assertNotIn("\n//signal/" + name, text)
        # ...and the start sequence is the one these tests drive.
        begin = text.index("=== universe_map_begin")
        order = [text.index(call, begin) for call in (
            "\n    universe_save_reset()", "\n    universe_set_active_save(",
            "\n    saved = universe_save_begin(START_MODE)", "\n    universe_load_players(",
            "\n    universe_save_ready()", "\n    task_schedule(universe_save_loop)")]
        self.assertEqual(order, sorted(order))


class Version2(SaveHarness):
    """Ships are filed under a stable id. Every version-1 fixture climbs the ladder."""

    def test_the_migration_on_each_fixture(self):
        for fixture in FIXTURE_NAMES:
            with self.subTest(fixture):
                shutil.rmtree(os.path.dirname(self.path), ignore_errors=True)
                self.launch()
                original = self.install(fixture)
                v1 = fs.load_yaml_data(self.path)
                self.assertEqual(v1["save_version"], 1)
                v2 = self.fn("universe_load")()
                self.assertEqual(v2["save_version"], 2)
                self.assertEqual(list(v2["players"]), ["artemis"])
                self.assertEqual(v2["players"]["artemis"],
                                 dict(v1["players"]["Artemis"], name="Artemis"))
                for key in v1:
                    if key not in ("players", "save_version"):
                        self.assertEqual(v2[key], v1[key], key)
                self.assertEqual(sorted(v2), sorted(v1))
                # Loading does not rewrite the save; it leaves the original beside it.
                self.assertEqual(_read_bytes(self.path), original)
                self.assertEqual(_read_bytes(self.path + ".v1.bak"), original)

    def test_the_first_continue_upgrades_and_keeps_the_original(self):
        original = self.install("v1_default.yaml")
        self.ship("Artemis")
        self.finish("Continue", self.begin("Continue"))
        self.assertIn("upgraded from version 1 to 2", self.fn("universe_save_report")("Continue"))
        upgraded = _read_bytes(self.path)
        self.assertNotEqual(upgraded, original)
        self.assertEqual(_read_bytes(self.path + ".v1.bak"), original)
        self.launch()                                  # the next launch
        self.ship("Artemis")
        self.finish("Continue", self.begin("Continue"))
        self.assertEqual(_read_bytes(self.path + ".v1.bak"), original)
        self.assertNotIn("upgraded", self.fn("universe_save_report")("Continue"))
        self.assertEqual(self.files(), ["universe_save_round_trip_1.yaml",
                                        "universe_save_round_trip_1.yaml.v1.bak"])

    def test_two_names_with_one_slug_get_two_ids(self):
        out = self.fn("universe_migrate")({"save_version": 1, "players": {
            "Artemis": {"items": {"ore": 1}}, "ARTEMIS!": {"items": {"ore": 2}}, 1701: {}}})
        self.assertEqual(out["players"], {
            "artemis": {"items": {"ore": 1}, "name": "Artemis"},
            "artemis_2": {"items": {"ore": 2}, "name": "ARTEMIS!"},
            "1701": {"name": "1701"}})

    def test_a_record_says_who_it_is(self):
        artemis = self.ship("Artemis")
        self.fn("ship_set_cell")(artemis.id, 3, -2)
        self.finish("Continue", self.begin("Continue"))
        rec = self.fn("universe_load")()["players"]["artemis"]
        self.assertEqual((rec["name"], rec["side"], rec["cell"]), ("Artemis", "tsn", [3, -2]))
        self.assertEqual(self.fn("universe_ship_key")(artemis.id), "artemis")

    def test_keys_this_build_does_not_know_are_kept_verbatim(self):
        self.install("v1_default.yaml")
        data = self.fn("universe_load")()
        data["state"] = {"relics": {"vault": ["a", "b"]}, "boarding_facts": {"": ["x"]}}
        data["parked_quests"] = {"old_step": {"state": 99}}
        data["players"]["artemis"]["clocks"] = {"side_iron_patrol": 41.5}
        self.fn("universe_save_state")(data)
        self.launch()
        self.ship("Artemis")
        self.finish("Continue", self.begin("Continue"))
        self.fn("universe_save")(7, 1, 1, {})
        self.fn("universe_save_diplomacy")({})
        after = self.fn("universe_load")()
        self.assertEqual(after["state"], data["state"])
        self.assertEqual(after["parked_quests"], data["parked_quests"])
        self.assertEqual(after["players"]["artemis"]["clocks"], {"side_iron_patrol": 41.5})


class ShipIdentity(SaveHarness):
    """A renamed ship keeps its jobs and standing; a ship that sits an evening out keeps
    its record; nothing is handed to the wrong ship."""

    def play(self, *ships, fixture=None):
        """One launch: spawn, Continue, save. Returns the live ships by name."""
        self.launch()
        if fixture:
            self.install(fixture)
        live = {}
        for spec in ships:
            name, side = spec if isinstance(spec, tuple) else (spec, "tsn")
            live[name] = self.ship(name, side)
        self.finish("Continue", self.begin("Continue"))
        return live

    def give(self, ship, job, nerve):
        self.fn("universe_grant_delivery")(ship.id, 7, 0, 0)
        set_inventory_value(ship.id, "reputation", {"iron": {"nerve": nerve}})
        self.assertIsNotNone(quest_get(ship.id, job))
        self.fn("universe_save_players")()

    def test_GAP_5_a_renamed_ship_keeps_its_jobs_and_standing(self):
        live = self.play("Artemis")
        self.give(live["Artemis"], "cargo_0_0", 30)
        live = self.play("Kittiwake")
        kittiwake = live["Kittiwake"]
        self.assertEqual(quest_get_state(kittiwake.id, "cargo_0_0"), 1)
        self.assertEqual(get_inventory_value(kittiwake.id, "reputation"), {"iron": {"nerve": 30}})
        report = self.fn("universe_save_report")("Continue")
        self.assertIn("ship 'Kittiwake' continues the saved record of 'Artemis'", report)
        players = self.fn("universe_load")()["players"]
        self.assertEqual(list(players), ["artemis"], "one record, under the id it always had")
        self.assertEqual(players["artemis"]["name"], "Kittiwake")
        # ...and the launch after that finds it by name, with nothing to report.
        live = self.play("Kittiwake")
        self.assertEqual(quest_get_state(live["Kittiwake"].id, "cargo_0_0"), 1)
        self.assertNotIn("continues the saved record", self.fn("universe_save_report")("Continue"))

    def test_a_renamed_ship_in_a_version_1_save_keeps_them_too(self):
        live = self.play("Kittiwake", fixture="v1_default.yaml")
        kittiwake = live["Kittiwake"]
        self.assertEqual(quest_get_state(kittiwake.id, "side_iron_patrol"), 1)
        self.assertEqual(get_inventory_value(kittiwake.id, "reputation")["iron"]["nerve"], 25)
        players = self.fn("universe_load")()["players"]
        self.assertEqual(list(players), ["artemis"])
        self.assertEqual(len(players["artemis"]["quests"]), 17)

    def test_a_ship_that_sits_an_evening_out_keeps_its_record(self):
        live = self.play("Artemis", "Intrepid")
        self.give(live["Intrepid"], "cargo_0_0", 12)
        self.play("Artemis")
        players = self.fn("universe_load")()["players"]
        self.assertEqual(sorted(players), ["artemis", "intrepid"])
        self.assertIn("cargo_0_0", players["intrepid"]["quests"])
        self.assertIn("kept 1 saved ship record(s) with no ship flying this session: Intrepid",
                      self.fn("universe_save_report")("Continue"))
        live = self.play("Artemis", "Intrepid")
        self.assertEqual(quest_get_state(live["Intrepid"].id, "cargo_0_0"), 1)
        self.assertIsNone(quest_get(live["Artemis"].id, "cargo_0_0"))

    def test_two_candidates_is_a_doubt_so_nobody_is_paired(self):
        live = self.play("Artemis", "Intrepid")
        self.give(live["Artemis"], "cargo_0_0", 5)
        live = self.play("Kittiwake")
        self.assertIsNone(quest_get(live["Kittiwake"].id, "cargo_0_0"))
        players = self.fn("universe_load")()["players"]
        self.assertEqual(sorted(players), ["artemis", "intrepid", "kittiwake"])
        self.assertIn("cargo_0_0", players["artemis"]["quests"], "and nothing was lost")

    def test_a_record_is_not_handed_across_sides(self):
        live = self.play("Artemis")
        self.give(live["Artemis"], "cargo_0_0", 5)
        live = self.play(("Vanguard", "orion"))
        self.assertIsNone(quest_get(live["Vanguard"].id, "cargo_0_0"))
        self.assertEqual(sorted(self.fn("universe_load")()["players"]), ["artemis", "vanguard"])

    def test_a_new_ship_never_lands_on_an_absent_ships_id(self):
        # "Artemis!" slugs to the same id as the Artemis that is not flying tonight.
        live = self.play("Artemis", "Intrepid")
        self.give(live["Artemis"], "cargo_0_0", 5)
        live = self.play("Intrepid", ("Artemis!", "orion"))
        players = self.fn("universe_load")()["players"]
        self.assertEqual(sorted(players), ["artemis", "artemis_2", "intrepid"])
        self.assertEqual(players["artemis"]["name"], "Artemis")
        self.assertIn("cargo_0_0", players["artemis"]["quests"])

    def test_a_respawned_ship_is_the_same_ship(self):
        live = self.play("Artemis")
        # A respawn is a new object with the old name and none of the old inventory.
        set_inventory_value(live["Artemis"].id, "universe_ship_key", None)
        self.fn("universe_save_players")()
        self.assertEqual(list(self.fn("universe_load")()["players"]), ["artemis"])

    def test_a_side_that_sits_an_evening_out_keeps_its_credits(self):
        self.play("Artemis", ("Vanguard", "orion"))
        set_inventory_value(to_side_id("orion"), "credits", 900)
        self.fn("universe_save_players")()
        self.play("Artemis")
        self.assertEqual(self.fn("universe_load")()["side_credits"], {"tsn": 500, "orion": 900})


class KnownGaps(SaveHarness):
    """Faults that are known, measured, and not fixed yet. Each is an expected failure,
    so the day one is fixed the test says so."""

    @unittest.expectedFailure
    def test_GAP_6_a_step_deleted_from_the_universe_file_stays_deleted(self):
        # The writer removed `signal_3` from the file. The grant that runs before the
        # restore therefore does not make it - and the restore puts it back from the
        # save, title and text and all. Phase 2 parks it instead (it has to tell an
        # authored step from a generated job to do that, and a v1 save cannot).
        self.install("v1_story.yaml")
        self.ship("Artemis")
        self.finish("Continue", self.begin("Continue"))
        self.assertIsNone(quest_get(Agent.SHARED_ID, "signal_3"))


if __name__ == "__main__":
    unittest.main()
