"""The Open Universe save: what goes in comes back out.

Drives the REAL save and load functions (universe_core/universe_helpers.py, loaded
through MAST's own `import` the way a mission loads them) against the mock, on saves
that were GENERATED by playing sandbox copies headless:

  tests/saves/v1_default.yaml      the Default universe, three jumps in, seventeen jobs
                                   in hand, standing with six sides
  tests/saves/v1_story.yaml        The Fading Signal: one step done, one open, one hidden
  tests/saves/v1_ou_template.yaml  a mission made from the `ou` template (the author
                                   course's Kestrel Verge), two evenings in

All three are version 1, written before ships had a stable id. They are fixtures: they
are never rewritten, and every test works on a copy in a temp folder.

  tests/saves/v2_story.yaml        The Fading Signal again, written by the build that
                                   keeps story steps slim and stamps them `authored`
  tests/saves/v2_ruin.yaml         a universe with a ruin: a barrier opened, the piece
                                   taken, a fact learned in a hail, a clock half run

The story a Continue merges onto is GRANTED here the way universe_map_begin grants it
(quest_grant_amd, then universe_story_stamp) - from the real universe file where a test
edits one, else from the steps the save itself holds ("the file still has every step").

Run:  python -m unittest tests.test_save_roundtrip     (from the OpenUniverse folder)
"""
import copy
import os
import shutil
import sys
import tempfile
import unittest

_HERE = os.path.dirname(os.path.abspath(__file__))
OU_CORE = os.path.abspath(os.path.join(_HERE, "..", "universe_core"))
FIXTURES = os.path.join(_HERE, "saves")
SBS = os.path.abspath(os.path.join(_HERE, "..", "..", "sbs_utils"))
sys.path.insert(0, SBS)

from sbs_utils.fs import test_set_exe_dir
test_set_exe_dir()

import cosmos_dev.mock.sbs as mock_sbs
sys.modules.setdefault("sbs", mock_sbs)

import sbs_utils.fs as fs
import sbs_utils.mast_sbs.story_nodes  # noqa: F401
from sbs_utils.agent import Agent, clear_shared
from sbs_utils.handlerhooks import reset_mission_state
from sbs_utils.helpers import Context, FakeEvent, FrameContext
from sbs_utils.mast.mast_globals import MastGlobals
from sbs_utils.mast.maststory import MastStory
from sbs_utils.procedural.inventory import get_inventory_value, set_inventory_value
from sbs_utils.procedural import amd_relics as relics
from sbs_utils.procedural import boarding
from sbs_utils.procedural import persistence
from sbs_utils.procedural.quest import (quest_get, quest_get_data, quest_get_state,
                                        quest_set_key)
from sbs_utils.procedural.quest_driver import (quest_grant_amd, quest_mark_complete,
                                               quest_mark_failed, quest_on_signal,
                                               quest_tick_fail_after, quest_actions_owed)
from sbs_utils.procedural.timers import get_time_remaining, is_timer_set
from sbs_utils.procedural.sides import side_ensure, to_side_id
from sbs_utils.procedural.spawn import player_spawn
from sbs_utils.spaceobject import SpaceObject

FIXTURE_NAMES = ("v1_default.yaml", "v1_story.yaml", "v1_ou_template.yaml")
OU = os.path.abspath(os.path.join(_HERE, ".."))


def quest_states(tree, _prefix=""):
    """`{path: (state, progress)}` for a saved quest tree, whichever way it was written."""
    out = {}
    for key, rec in (tree or {}).items():
        out[_prefix + key] = (rec.get("state", 0), rec.get("progress", 0) or 0)
        out.update(quest_states(rec.get("children"), _prefix + key + "/"))
    return out


def story_file(name="scout_signal.amd"):
    with open(os.path.join(OU, name), encoding="utf-8") as f:
        return f.read().replace("\r\n", "\n")


def without_record(text, key):
    """A universe file with one `### [..](key)` record taken out."""
    lines = text.split("\n")
    start = next(i for i, l in enumerate(lines)
                 if l.startswith("#") and l.rstrip().endswith("(" + key + ")"))
    end = next((i for i in range(start + 1, len(lines)) if lines[i].startswith("#")),
               len(lines))
    return "\n".join(lines[:start] + lines[end:])


def with_field(text, key, line):
    """A universe file with one more fence line on the record keyed `key`."""
    lines = text.split("\n")
    start = next(i for i, l in enumerate(lines)
                 if l.startswith("#") and l.rstrip().endswith("(" + key + ")"))
    fence = next(i for i in range(start + 1, len(lines)) if lines[i].strip() == "---")
    return "\n".join(lines[:fence + 1] + [line] + lines[fence + 1:])


def _read_bytes(path):
    with open(path, "rb") as f:
        return f.read()


def players_by_name(data):
    """The ship records of a save, keyed by the ship's NAME - whichever version wrote
    it. Version 1 keyed `players` by name; version 2 keys it by a stable id and holds
    the name inside the record."""
    out = {}
    for key, rec in (data.get("players") or {}).items():
        out[rec.get("name", key) if isinstance(rec, dict) else key] = rec
    return out


class SaveHarness(unittest.TestCase):
    """The mission's Python, loaded once per class into its own namespace, with the
    saves folder pointed at a temp directory."""

    @classmethod
    def setUpClass(cls):
        cls.root = tempfile.mkdtemp(prefix="ou_save_test_")
        cls.mission = os.path.join(cls.root, "mission")
        os.makedirs(cls.mission)
        cls.old_script_dir = fs.script_dir
        # common_data is the mission folder's SIBLING, so this is what moves the saves.
        fs.script_dir = cls.mission
        cls.old_globals = dict(MastGlobals.globals)
        story = MastStory()
        story.basedir = OU_CORE
        # universe_amd / universe_doc: the universe's own reader, so a test grants a
        # story from the same parse universe_map_begin grants it from.
        cls.errors = story.compile("import universe_helpers.py\nimport universe_amd.py\n"
                                   "import universe_doc.py\n", "save_harness", story)
        cls.story = story

    @classmethod
    def tearDownClass(cls):
        MastGlobals.globals.clear()
        MastGlobals.globals.update(cls.old_globals)
        fs.script_dir = cls.old_script_dir
        shutil.rmtree(cls.root, ignore_errors=True)

    def setUp(self):
        self.assertEqual(self.errors, [])
        shutil.rmtree(os.path.join(self.root, "common_data"), ignore_errors=True)
        self.launch()

    def launch(self):
        """A fresh process as far as the game can tell: a new sim, no ships, no shared
        state - and whatever is in the saves folder still there. A test that plays two
        evenings calls this between them."""
        fs.script_dir = self.mission
        # The library's own per-mission reset, which is what a new process amounts to
        # for everything the LIBRARY keeps (facts, a ruin's ledger, quest timers).
        reset_mission_state()
        fs.script_dir = self.mission
        mock_sbs.create_new_sim()
        mock_sbs.resume_sim()
        SpaceObject.clear()
        clear_shared()
        FrameContext.context = Context(mock_sbs.sim, mock_sbs, FakeEvent(0, "test"))
        FrameContext.page = None
        Agent.SHARED.set_inventory_value("sim", mock_sbs.sim)
        reset = MastGlobals.globals.get("universe_save_reset")
        if reset is not None:
            reset()
        self.fn("universe_set_active_save")("Round Trip", 1)
        self.path = self.fn("universe_save_path")()
        # A test that resolves the real saves folder is a defect, so say so before
        # anything is written.
        inside = os.path.normcase(os.path.abspath(self.path)).startswith(
            os.path.normcase(os.path.abspath(self.root)))
        self.assertTrue(inside, "the save path left the temp folder: " + self.path)

    def tearDown(self):
        FrameContext.context = None

    def fn(self, name):
        return MastGlobals.globals[name]

    def module_globals(self):
        """universe_helpers.py's own namespace - where its private names live."""
        return self.fn("universe_save_players").__globals__

    def install(self, fixture):
        """Put a copy of a fixture where the active save is read from."""
        os.makedirs(os.path.dirname(self.path), exist_ok=True)
        shutil.copyfile(os.path.join(FIXTURES, fixture), self.path)
        return _read_bytes(self.path)

    def write_save(self, text):
        os.makedirs(os.path.dirname(self.path), exist_ok=True)
        with open(self.path, "w", encoding="utf-8", newline="\n") as f:
            f.write(text)
        return _read_bytes(self.path)

    def ship(self, name, side="tsn"):
        side_ensure(side)
        return player_spawn(0, 0, 0, name, side, "tsn_light_cruiser").py_object

    def files(self):
        folder = os.path.dirname(self.path)
        return sorted(os.listdir(folder)) if os.path.isdir(folder) else []

    def begin(self, mode):
        """What universe_map_begin does with the save before anything is spawned."""
        return self.fn("universe_save_begin")(mode)

    def grant(self, text):
        """Grant a universe file's story the way universe_map_begin does: the narrative
        and then the goals, each stamped as the file's own."""
        doc = self.fn("universe_doc")(text)
        for section in ("narrative", "goals"):
            node = self.fn("universe_section")(doc, section)
            quest_grant_amd(Agent.SHARED_ID, node)
            self.stamp(node)

    def stamp(self, node):
        # (Looked up, not called by name: run against a build from before the stamp
        # existed, the tests should fail for what that build DOES, not for a NameError.)
        stamp = MastGlobals.globals.get("universe_story_stamp")
        if stamp is not None:
            stamp(Agent.SHARED_ID, node)

    def grant_what_the_save_holds(self, saved):
        """"The universe file still has every step": grant the story steps a save holds,
        from the save's own copy of them. For a fixture whose universe file is not in
        this repo, and for the tests that are not about the file changing."""
        def authored(rec):
            data = rec.get("data")
            return (rec.get("authored") or "display_text" not in rec
                    or (isinstance(data, dict) and "scope" in data))

        def as_doc(tree):
            kids = []
            for key, rec in (tree or {}).items():
                if not authored(rec):
                    continue
                kids.append({"key": key, "display_text": rec.get("display_text", key),
                             "description": rec.get("description", ""),
                             "data": copy.deepcopy(rec.get("data")) or {},
                             "children": as_doc(rec.get("children"))["children"]})
            return {"children": kids}
        doc = as_doc((saved or {}).get("shared_quests"))
        quest_grant_amd(Agent.SHARED_ID, doc)
        self.stamp(doc)

    def finish(self, mode, saved, seed=7, story=None):
        """...and what it does once the ships exist. `story` is the universe file's
        text; without one the story is whatever the save holds."""
        if saved is None:
            self.fn("universe_save")(seed, 0, 0, {})
        else:
            cur = saved.get("current_system", [0, 0])
            self.fn("universe_save")(saved.get("universe_seed", 1), cur[0], cur[1],
                                     saved.get("systems", {}))
        if story is not None:
            self.grant(story)
        else:
            self.grant_what_the_save_holds(saved)
        self.fn("universe_load_players")(mode == "Continue")
        self.fn("universe_save_ready")()
        self.fn("universe_save_players")()


class RoundTrip(SaveHarness):
    """Load, restore onto ships, save, load again: nothing is lost and nothing moves."""

    def round_trip(self, fixture):
        self.install(fixture)
        before = copy.deepcopy(self.fn("universe_load")())
        self.assertIsNotNone(before)
        ships = {name: self.ship(name) for name in players_by_name(before)}
        saved = self.begin("Continue")
        self.assertIsNotNone(saved)
        self.finish("Continue", saved)
        after = self.fn("universe_load")()
        return before, after, ships

    def assert_same_campaign(self, before, after):
        for key in ("universe_seed", "current_system", "systems", "side_credits",
                    "side_admiralty"):
            self.assertEqual(after.get(key), before.get(key), key)
        # Every step and every job, in the state it was in. (A story step is saved slim
        # now - its state, not its text - so the records are compared by what they SAY.)
        self.assertEqual(quest_states(after.get("shared_quests")),
                         quest_states(before.get("shared_quests")))
        self.assertNotIn("parked_quests", after, "the file still has every step")
        was, now = players_by_name(before), players_by_name(after)
        self.assertEqual(sorted(now), sorted(was))
        for name, rec in was.items():
            for field in ("items", "installs", "quests", "reputation"):
                self.assertEqual(now[name].get(field), rec.get(field), f"{name}.{field}")

    def test_the_default_universe_comes_back_whole(self):
        before, after, ships = self.round_trip("v1_default.yaml")
        self.assert_same_campaign(before, after)
        artemis = ships["Artemis"]
        # Not only in the file: on the ship.
        self.assertEqual(quest_get_state(artemis.id, "cargo_0_0"), 1)
        self.assertEqual(quest_get_state(artemis.id, "side_iron_patrol"), 1)
        self.assertEqual(get_inventory_value(artemis.id, "reputation")["iron"]["nerve"], 25)
        self.assertEqual(get_inventory_value(to_side_id("tsn"), "credits"), 500)
        self.assertEqual(after["current_system"], [2, 1])

    def test_a_story_keeps_its_done_open_and_hidden_steps(self):
        before, after, _ = self.round_trip("v1_story.yaml")
        self.assert_same_campaign(before, after)
        states = {key: quest_get_state(Agent.SHARED_ID, key)
                  for key in ("signal_1", "signal_2", "signal_3")}
        self.assertEqual(states, {"signal_1": 99, "signal_2": 1, "signal_3": 2})

    def test_an_ou_template_mission_comes_back_whole(self):
        before, after, ships = self.round_trip("v1_ou_template.yaml")
        self.assert_same_campaign(before, after)
        self.assertEqual(quest_get_state(Agent.SHARED_ID, "s02_home"), 99)
        self.assertEqual(quest_get_state(Agent.SHARED_ID, "s03_go"), 1)
        self.assertEqual(quest_get_state(Agent.SHARED_ID, "act1_close"), 2)
        self.assertIsNotNone(quest_get(Agent.SHARED_ID, "waypoints/wp_2_2"))
        # A charted location is GENERATED: nothing re-makes it, so it is saved whole.
        self.assertEqual(after["shared_quests"]["waypoints"],
                         before["shared_quests"]["waypoints"])
        self.assertEqual(get_inventory_value(ships["Artemis"].id, "reputation"),
                         {"hollin": {"honesty": 40, "generosity": 40}})
        self.assertEqual(get_inventory_value(to_side_id("tsn"), "credits"), 1150)

    def test_a_second_round_trip_changes_nothing(self):
        self.install("v1_default.yaml")
        self.ship("Artemis")
        self.finish("Continue", self.begin("Continue"))
        once = _read_bytes(self.path)
        self.fn("universe_save_players")()
        self.assertEqual(_read_bytes(self.path), once)


def _boom(data):
    raise ValueError("migration step 1 is broken")


class Safety(SaveHarness):
    """A save that will not load is never written over, and a New Game is a new game."""

    def break_the_ladder(self):
        g = self.module_globals()
        old = g["_MIGRATIONS"]
        g["_MIGRATIONS"] = {1: _boom}
        self.addCleanup(g.__setitem__, "_MIGRATIONS", old)

    def play_an_evening(self, mode, saved):
        """Everything that writes the save during play."""
        self.ship("Artemis")
        self.finish(mode, saved)
        self.fn("universe_save")(7, 3, 3, {"3,3": {"visited": True}})
        self.fn("universe_save_diplomacy")({"tsn|iron": 2})
        self.fn("universe_save_request")()
        self.fn("universe_save_flush")()
        self.fn("universe_save_state")({"universe_seed": 1})

    def test_GAP_11_a_save_that_will_not_migrate_is_left_alone_with_a_copy(self):
        original = self.install("v1_default.yaml")
        self.break_the_ladder()
        saved = self.begin("Continue")
        self.assertIsNone(saved, "the evening still plays, as a new game")
        self.play_an_evening("Continue", saved)
        self.assertEqual(_read_bytes(self.path), original)
        self.assertEqual(_read_bytes(self.path + ".v1.bak"), original)
        self.assertEqual(self.files(), ["universe_save_round_trip_1.yaml",
                                        "universe_save_round_trip_1.yaml.v1.bak"])
        why = self.fn("universe_save_blocked")()
        self.assertIn("could not be loaded", why)
        self.assertIn("migration step 1 is broken", why)
        self.assertIn("universe_save_round_trip_1.yaml.v1.bak", why)
        self.assertIn(why, self.fn("universe_save_report")("Continue"))

    def test_GAP_11_an_unreadable_save_is_left_alone_with_a_copy(self):
        original = self.write_save("players: [unclosed\n  nope: : :\n")
        saved = self.begin("Continue")
        self.assertIsNone(saved)
        self.play_an_evening("Continue", saved)
        self.assertEqual(_read_bytes(self.path), original)
        self.assertEqual(_read_bytes(self.path + ".unreadable.bak"), original)
        self.assertIn("unreadable", self.fn("universe_save_blocked")())

    def test_a_save_from_a_newer_build_is_played_and_not_written_over(self):
        original = self.write_save("save_version: 9\nuniverse_seed: 5\ncurrent_system:\n- 4\n- 4\n")
        saved = self.begin("Continue")
        self.assertEqual(saved["universe_seed"], 5)
        self.play_an_evening("Continue", saved)
        self.assertEqual(_read_bytes(self.path), original)
        self.assertIn("newer build", self.fn("universe_save_blocked")())

    def test_a_write_that_meets_a_broken_file_mid_session_stops_too(self):
        # Not through universe_save_begin: the file goes bad while the game is running.
        self.ship("Artemis")
        self.finish("Continue", self.begin("Continue"))
        original = self.write_save("players: [unclosed\n")
        self.fn("universe_save")(7, 1, 1, {})
        self.fn("universe_save_players")()
        self.assertEqual(_read_bytes(self.path), original)
        self.assertEqual(_read_bytes(self.path + ".unreadable.bak"), original)

    def test_continue_with_no_file_starts_one(self):
        self.assertIsNone(self.begin("Continue"))
        self.ship("Artemis")
        self.finish("Continue", None)
        data = self.fn("universe_load")()
        self.assertEqual(data["save_version"], 2)
        self.assertEqual(list(data["players"]), ["artemis"])
        self.assertEqual(self.fn("universe_save_blocked")(), "")

    def test_GAP_12_a_new_game_does_not_inherit_the_old_diplomacy(self):
        original = self.install("v1_default.yaml")
        self.ship("Artemis")
        self.finish("Continue", self.begin("Continue"))
        self.fn("universe_save_diplomacy")({"tsn|iron": 2})
        self.fn("universe_save_state")(dict(self.fn("universe_load")(), state={"relics": {"a": 1}}))
        old_campaign = _read_bytes(self.path)
        self.launch()                                  # the next launch
        self.ship("Artemis")
        saved = self.begin("New Game")
        self.assertIsNone(saved)
        self.finish("New Game", saved)
        data = self.fn("universe_load")()
        self.assertEqual(data.get("diplomacy", {}), {})
        self.assertNotIn("state", data, "a section this build does not know is the old "
                                        "campaign's too")
        self.assertEqual(data["players"]["artemis"]["quests"], {})
        self.assertEqual(data["current_system"], [0, 0])
        # The campaign that was there is one file away, and so is the version-1 original.
        self.assertEqual(_read_bytes(self.path + ".previous.bak"), old_campaign)
        self.assertEqual(_read_bytes(self.path + ".v1.bak"), original)

    def test_a_new_game_over_a_broken_file_keeps_a_copy_and_saves(self):
        original = self.write_save("players: [unclosed\n")
        self.ship("Artemis")
        self.finish("New Game", self.begin("New Game"))
        self.assertEqual(_read_bytes(self.path + ".previous.bak"), original)
        self.assertEqual(self.fn("universe_save_blocked")(), "")
        self.assertEqual(list(self.fn("universe_load")()["players"]), ["artemis"])


class SaveRequest(SaveHarness):
    """Quest changes ask for a save; one write serves a burst; nothing is written while
    the campaign is still loading."""

    def test_nothing_writes_players_until_the_campaign_is_restored(self):
        original = self.install("v1_default.yaml")
        self.ship("Artemis")
        saved = self.begin("Continue")
        # universe_map_begin has reset the session (setUp did) and has not said ready.
        # The ship is spawned and EMPTY; a save now would write that over its jobs.
        self.assertFalse(self.fn("universe_save_players")())
        self.assertFalse(self.fn("universe_save_flush")())
        self.assertEqual(_read_bytes(self.path), original)
        self.assertTrue(self.fn("universe_save_pending")(), "asked for, not forgotten")
        self.finish("Continue", saved)
        self.assertFalse(self.fn("universe_save_pending")())
        jobs = players_by_name(self.fn("universe_load")())["Artemis"]["quests"]
        self.assertEqual(len(jobs), 17)

    def test_a_burst_of_requests_is_one_write(self):
        self.ship("Artemis")
        self.finish("Continue", self.begin("Continue"))
        self.assertFalse(self.fn("universe_save_flush")(), "nothing asked for")
        g = self.module_globals()
        writes = []
        real = g["_universe_write"]
        g["_universe_write"] = lambda change: writes.append(1) or real(change)
        self.addCleanup(g.__setitem__, "_universe_write", real)
        for _ in range(5):
            self.fn("universe_save_request")()
        self.assertTrue(self.fn("universe_save_flush")())
        self.assertFalse(self.fn("universe_save_flush")())
        self.assertEqual(len(writes), 1)

    def test_a_failed_step_reaches_the_file_without_a_jump(self):
        self.install("v1_default.yaml")
        artemis = self.ship("Artemis")
        self.finish("Continue", self.begin("Continue"))
        quest_set_key(artemis.id, "cargo_0_0", "state", 98)
        quest_set_key(Agent.SHARED_ID, "truce_1", "state", 99)
        self.fn("universe_save_request")()
        self.assertTrue(self.fn("universe_save_flush")())
        data = self.fn("universe_load")()
        self.assertEqual(players_by_name(data)["Artemis"]["quests"]["cargo_0_0"]["state"], 98)
        self.assertEqual(data["shared_quests"]["truce_1"]["state"], 99)

    def test_the_routes_that_ask_are_server_routes(self):
        with open(os.path.join(OU_CORE, "universe.mast"), encoding="utf-8") as f:
            text = f.read()
        for name in ("quest_succeeded", "quest_failed_done", "quest_started"):
            start = text.index("//shared/signal/" + name + " if UNIVERSE_ACTIVE")
            end = text.index("\n\n\n", start) if name == "quest_succeeded" else text.index("\n\n", start)
            self.assertIn("universe_save_request()", text[start:end], name)
            self.assertNotIn("\n//signal/" + name, text)
        # ...and the start sequence is the one these tests drive.
        begin = text.index("=== universe_map_begin")
        order = [text.index(call, begin) for call in (
            "\n    universe_save_reset()", "\n    universe_set_active_save(",
            "\n    saved = universe_save_begin(START_MODE)", "\n    universe_load_players(",
            "\n    universe_save_ready()", "\n    task_schedule(universe_save_loop)")]
        self.assertEqual(order, sorted(order))


class Version2(SaveHarness):
    """Ships are filed under a stable id. Every version-1 fixture climbs the ladder."""

    def test_the_migration_on_each_fixture(self):
        for fixture in FIXTURE_NAMES:
            with self.subTest(fixture):
                shutil.rmtree(os.path.dirname(self.path), ignore_errors=True)
                self.launch()
                original = self.install(fixture)
                v1 = fs.load_yaml_data(self.path)
                self.assertEqual(v1["save_version"], 1)
                v2 = self.fn("universe_load")()
                self.assertEqual(v2["save_version"], 2)
                self.assertEqual(list(v2["players"]), ["artemis"])
                self.assertEqual(v2["players"]["artemis"],
                                 dict(v1["players"]["Artemis"], name="Artemis"))
                for key in v1:
                    if key not in ("players", "save_version"):
                        self.assertEqual(v2[key], v1[key], key)
                self.assertEqual(sorted(v2), sorted(v1))
                # Loading does not rewrite the save; it leaves the original beside it.
                self.assertEqual(_read_bytes(self.path), original)
                self.assertEqual(_read_bytes(self.path + ".v1.bak"), original)

    def test_the_first_continue_upgrades_and_keeps_the_original(self):
        original = self.install("v1_default.yaml")
        self.ship("Artemis")
        self.finish("Continue", self.begin("Continue"))
        self.assertIn("upgraded from version 1 to 2", self.fn("universe_save_report")("Continue"))
        upgraded = _read_bytes(self.path)
        self.assertNotEqual(upgraded, original)
        self.assertEqual(_read_bytes(self.path + ".v1.bak"), original)
        self.launch()                                  # the next launch
        self.ship("Artemis")
        self.finish("Continue", self.begin("Continue"))
        self.assertEqual(_read_bytes(self.path + ".v1.bak"), original)
        self.assertNotIn("upgraded", self.fn("universe_save_report")("Continue"))
        self.assertEqual(self.files(), ["universe_save_round_trip_1.yaml",
                                        "universe_save_round_trip_1.yaml.v1.bak"])

    def test_two_names_with_one_slug_get_two_ids(self):
        out = self.fn("universe_migrate")({"save_version": 1, "players": {
            "Artemis": {"items": {"ore": 1}}, "ARTEMIS!": {"items": {"ore": 2}}, 1701: {}}})
        self.assertEqual(out["players"], {
            "artemis": {"items": {"ore": 1}, "name": "Artemis"},
            "artemis_2": {"items": {"ore": 2}, "name": "ARTEMIS!"},
            "1701": {"name": "1701"}})

    def test_a_record_says_who_it_is(self):
        artemis = self.ship("Artemis")
        self.fn("ship_set_cell")(artemis.id, 3, -2)
        self.finish("Continue", self.begin("Continue"))
        rec = self.fn("universe_load")()["players"]["artemis"]
        self.assertEqual((rec["name"], rec["side"], rec["cell"]), ("Artemis", "tsn", [3, -2]))
        self.assertEqual(self.fn("universe_ship_key")(artemis.id), "artemis")

    def test_keys_this_build_does_not_know_are_kept_verbatim(self):
        self.install("v1_default.yaml")
        data = self.fn("universe_load")()
        # A section, a state provider and a ship field that a LATER build (or an addon
        # that is not loaded tonight) wrote. `state` itself is known now; what is under
        # it is each provider's own, and a name nobody claims is still passed through.
        data["later_section"] = {"anything": [1, 2, {"deep": True}]}
        data["state"] = {"an_addon_not_loaded_tonight": {"vault": ["a", "b"]}}
        data["players"]["artemis"]["later_field"] = {"side_iron_patrol": 41.5}
        self.fn("universe_save_state")(data)
        self.launch()
        self.ship("Artemis")
        self.finish("Continue", self.begin("Continue"))
        self.fn("universe_save")(7, 1, 1, {})
        self.fn("universe_save_diplomacy")({})
        self.fn("universe_save_players")()
        after = self.fn("universe_load")()
        self.assertEqual(after["later_section"], data["later_section"])
        self.assertEqual(after["state"], data["state"])
        self.assertEqual(after["players"]["artemis"]["later_field"], {"side_iron_patrol": 41.5})


class ShipIdentity(SaveHarness):
    """A renamed ship keeps its jobs and standing; a ship that sits an evening out keeps
    its record; nothing is handed to the wrong ship."""

    def play(self, *ships, fixture=None):
        """One launch: spawn, Continue, save. Returns the live ships by name."""
        self.launch()
        if fixture:
            self.install(fixture)
        live = {}
        for spec in ships:
            name, side = spec if isinstance(spec, tuple) else (spec, "tsn")
            live[name] = self.ship(name, side)
        self.finish("Continue", self.begin("Continue"))
        return live

    def give(self, ship, job, nerve):
        self.fn("universe_grant_delivery")(ship.id, 7, 0, 0)
        set_inventory_value(ship.id, "reputation", {"iron": {"nerve": nerve}})
        self.assertIsNotNone(quest_get(ship.id, job))
        self.fn("universe_save_players")()

    def test_GAP_5_a_renamed_ship_keeps_its_jobs_and_standing(self):
        live = self.play("Artemis")
        self.give(live["Artemis"], "cargo_0_0", 30)
        live = self.play("Kittiwake")
        kittiwake = live["Kittiwake"]
        self.assertEqual(quest_get_state(kittiwake.id, "cargo_0_0"), 1)
        self.assertEqual(get_inventory_value(kittiwake.id, "reputation"), {"iron": {"nerve": 30}})
        report = self.fn("universe_save_report")("Continue")
        self.assertIn("ship 'Kittiwake' continues the saved record of 'Artemis'", report)
        players = self.fn("universe_load")()["players"]
        self.assertEqual(list(players), ["artemis"], "one record, under the id it always had")
        self.assertEqual(players["artemis"]["name"], "Kittiwake")
        # ...and the launch after that finds it by name, with nothing to report.
        live = self.play("Kittiwake")
        self.assertEqual(quest_get_state(live["Kittiwake"].id, "cargo_0_0"), 1)
        self.assertNotIn("continues the saved record", self.fn("universe_save_report")("Continue"))

    def test_a_renamed_ship_in_a_version_1_save_keeps_them_too(self):
        live = self.play("Kittiwake", fixture="v1_default.yaml")
        kittiwake = live["Kittiwake"]
        self.assertEqual(quest_get_state(kittiwake.id, "side_iron_patrol"), 1)
        self.assertEqual(get_inventory_value(kittiwake.id, "reputation")["iron"]["nerve"], 25)
        players = self.fn("universe_load")()["players"]
        self.assertEqual(list(players), ["artemis"])
        self.assertEqual(len(players["artemis"]["quests"]), 17)

    def test_a_ship_that_sits_an_evening_out_keeps_its_record(self):
        live = self.play("Artemis", "Intrepid")
        self.give(live["Intrepid"], "cargo_0_0", 12)
        self.play("Artemis")
        players = self.fn("universe_load")()["players"]
        self.assertEqual(sorted(players), ["artemis", "intrepid"])
        self.assertIn("cargo_0_0", players["intrepid"]["quests"])
        self.assertIn("kept 1 saved ship record(s) with no ship flying this session: Intrepid",
                      self.fn("universe_save_report")("Continue"))
        live = self.play("Artemis", "Intrepid")
        self.assertEqual(quest_get_state(live["Intrepid"].id, "cargo_0_0"), 1)
        self.assertIsNone(quest_get(live["Artemis"].id, "cargo_0_0"))

    def test_two_candidates_is_a_doubt_so_nobody_is_paired(self):
        live = self.play("Artemis", "Intrepid")
        self.give(live["Artemis"], "cargo_0_0", 5)
        live = self.play("Kittiwake")
        self.assertIsNone(quest_get(live["Kittiwake"].id, "cargo_0_0"))
        players = self.fn("universe_load")()["players"]
        self.assertEqual(sorted(players), ["artemis", "intrepid", "kittiwake"])
        self.assertIn("cargo_0_0", players["artemis"]["quests"], "and nothing was lost")

    def test_a_record_is_not_handed_across_sides(self):
        live = self.play("Artemis")
        self.give(live["Artemis"], "cargo_0_0", 5)
        live = self.play(("Vanguard", "orion"))
        self.assertIsNone(quest_get(live["Vanguard"].id, "cargo_0_0"))
        self.assertEqual(sorted(self.fn("universe_load")()["players"]), ["artemis", "vanguard"])

    def test_a_new_ship_never_lands_on_an_absent_ships_id(self):
        # "Artemis!" slugs to the same id as the Artemis that is not flying tonight.
        live = self.play("Artemis", "Intrepid")
        self.give(live["Artemis"], "cargo_0_0", 5)
        live = self.play("Intrepid", ("Artemis!", "orion"))
        players = self.fn("universe_load")()["players"]
        self.assertEqual(sorted(players), ["artemis", "artemis_2", "intrepid"])
        self.assertEqual(players["artemis"]["name"], "Artemis")
        self.assertIn("cargo_0_0", players["artemis"]["quests"])

    def test_a_respawned_ship_is_the_same_ship(self):
        live = self.play("Artemis")
        # A respawn is a new object with the old name and none of the old inventory.
        set_inventory_value(live["Artemis"].id, "universe_ship_key", None)
        self.fn("universe_save_players")()
        self.assertEqual(list(self.fn("universe_load")()["players"]), ["artemis"])

    def test_a_side_that_sits_an_evening_out_keeps_its_credits(self):
        self.play("Artemis", ("Vanguard", "orion"))
        set_inventory_value(to_side_id("orion"), "credits", 900)
        self.fn("universe_save_players")()
        self.play("Artemis")
        self.assertEqual(self.fn("universe_load")()["side_credits"], {"tsn": 500, "orion": 900})


# A small story with the shapes the Fading Signal does not have: a nested arc, a step
# that waits on a start trigger, a step on a clock, and a step with an `Action:`.
SHAPES = """# [Shapes](shapes)
---
Universe
---

## [Narrative](narrative)

### [The Arc](arc)
---
Scope: shared
State: active
---
The whole of it.

#### [Step One](one)
---
Scope: shared
State: active
Done when: signal one_done
Then: reveal arc/two
---

#### [Step Two](two)
---
Scope: shared
State: secret
Done when: signal two_done
---

### [The Alarm](alarm)
---
Scope: shared
State: active
Starts when: signal alarm_raised
Done when: signal alarm_cleared
---
Waits for the alarm, then for the all-clear.

### [The Countdown](countdown)
---
Scope: shared
State: active
Done when: signal reached_port
Fails when: 60 seconds
---
Sixty seconds to make port.

### [The Greeting](greeting)
---
Scope: shared
State: active
Done when: signal greeted
Then: learn the yard is open
Action:
  - yard becomes open
---
Runs the moment the story starts.
"""


class Evenings(SaveHarness):
    """Whole evenings: launch, ships, open the save, grant the story from a universe
    file, restore, save. `self.file` is the universe file tonight."""

    file = None

    def evening(self, story=None, mode="Continue", ships=("Artemis",)):
        self.launch()
        live = {}
        for spec in ships:
            name, side = spec if isinstance(spec, tuple) else (spec, "tsn")
            live[name] = self.ship(name, side)
        saved = self.begin(mode)
        self.finish(mode, saved, story=story if story is not None else self.file)
        self.live = live
        return live

    def save(self):
        self.assertTrue(self.fn("universe_save_players")())
        return self.fn("universe_load")()

    def state(self, key):
        return quest_get_state(Agent.SHARED_ID, key)

    def seconds(self, n):
        mock_sbs.sim._time_tick_counter += int(n * 30)


class StoryRevisions(Evenings):
    """The writer edits the universe file between evenings: takes a step out, puts it
    back, renames one. The save follows the file instead of fighting it."""

    file = story_file()

    def play_to_the_hulk(self):
        """Evening one of The Fading Signal: both jumps made, the scan still to do."""
        self.evening(mode="New Game")
        quest_mark_complete(Agent.SHARED_ID, "signal_1")
        quest_mark_complete(Agent.SHARED_ID, "signal_2")
        self.assertEqual([self.state(k) for k in ("signal_1", "signal_2", "signal_3")],
                         [99, 99, 1])
        return self.save()

    def test_GAP_6_a_step_deleted_from_the_universe_file_stays_deleted(self):
        # A version-1 save, and the writer has removed `signal_3` from the file. The
        # grant that runs before the restore does not make it - and the restore used to
        # put it back from the save, title and text and all.
        self.install("v1_story.yaml")
        self.evening(without_record(self.file, "signal_3"))
        self.assertIsNone(quest_get(Agent.SHARED_ID, "signal_3"))
        self.assertEqual([self.state(k) for k in ("signal_1", "signal_2")], [99, 1],
                         "the steps the file still has are as they were")

    def test_it_is_parked_not_deleted(self):
        self.install("v1_story.yaml")
        self.evening(without_record(self.file, "signal_3"))
        self.assertEqual(self.fn("universe_parked_quests")(), ["signal_3"])
        data = self.fn("universe_load")()
        self.assertNotIn("signal_3", data["shared_quests"])
        self.assertEqual(data["parked_quests"]["shared"]["signal_3"]["state"], 2)
        self.assertIn("parked 1 story step(s)", self.fn("universe_save_report")("Continue"))

    def test_a_parked_step_is_put_back_when_its_record_returns(self):
        self.play_to_the_hulk()
        self.evening(without_record(self.file, "signal_3"))
        self.assertIsNone(quest_get(Agent.SHARED_ID, "signal_3"))
        self.evening(without_record(self.file, "signal_3"))      # ...for as long as it takes
        self.assertEqual(self.fn("universe_parked_quests")(), ["signal_3"])
        self.evening()                                           # the record is back
        self.assertEqual(self.state("signal_3"), 1, "running, as it was left")
        self.assertEqual(self.fn("universe_parked_quests")(), [])
        self.assertNotIn("parked_quests", self.fn("universe_load")())
        self.assertIn("re-attached 1 parked story step(s)",
                      self.fn("universe_save_report")("Continue"))

    def test_a_generated_job_is_still_restored_from_the_save(self):
        """The branch that used to bring a deleted step back is the one that restores a
        cargo run and a charted location - nothing re-makes those."""
        live = self.evening(mode="New Game")
        self.fn("universe_grant_delivery")(live["Artemis"].id, 7, 0, 0)
        self.fn("universe_add_waypoint")(Agent.SHARED_ID, 2, 2, "The Wren")
        self.save()
        live = self.evening()
        self.assertEqual(quest_get_state(live["Artemis"].id, "cargo_0_0"), 1)
        self.assertIsNotNone(quest_get(Agent.SHARED_ID, "waypoints/wp_2_2"))
        self.assertEqual(self.fn("universe_parked_quests")(), [])

    def test_GAP_10_no_step_text_is_in_the_save(self):
        self.play_to_the_hulk()
        raw = _read_bytes(self.path).decode("utf-8")
        for words in ("The Long Quiet", "cold hulk", "A Voice in the Static", "Citation",
                      "on_scan", "universe_derelict"):
            self.assertNotIn(words, raw, words)
        rec = self.fn("universe_load")()["shared_quests"]["signal_3"]
        self.assertEqual(rec, {"authored": True, "state": 1, "progress": 0, "children": {}})

    def test_the_step_text_that_plays_is_the_files(self):
        self.play_to_the_hulk()
        self.evening(self.file.replace("[The Long Quiet]", "[The Longer Quiet]"))
        self.assertEqual(quest_get(Agent.SHARED_ID, "signal_3").get("display_text"),
                         "The Longer Quiet")
        self.assertEqual(self.state("signal_3"), 1)

    def test_a_version_1_save_is_slim_after_its_first_continue(self):
        self.install("v1_story.yaml")
        self.evening()
        data = self.fn("universe_load")()
        self.assertEqual(quest_states(data["shared_quests"]),
                         {"signal_1": (99, 0), "signal_2": (1, 0), "signal_3": (2, 0),
                          "goal_answer": (1, 0)})
        for key, rec in data["shared_quests"].items():
            self.assertTrue(rec.get("authored"), key)
            self.assertNotIn("description", rec, key)

    # -- Was: ---------------------------------------------------------------------------
    def renamed(self, was=True):
        text = self.file.replace("(signal_2)", "(cold_trail)").replace(
            "Then: reveal signal_2", "Then: reveal cold_trail")
        return with_field(text, "cold_trail", "Was: signal_2") if was else text

    def test_GAP_7_a_renamed_step_starts_again_and_its_old_key_is_not_a_ghost(self):
        """Renamed with no `Was:`. The old key no longer comes back as a second step -
        it is parked - but nothing says the new key is the same step, so it is fresh."""
        self.evening(mode="New Game")
        quest_mark_complete(Agent.SHARED_ID, "signal_1")
        self.assertEqual(self.state("signal_2"), 1)
        self.save()
        self.evening(self.renamed(was=False))
        self.assertIsNone(quest_get(Agent.SHARED_ID, "signal_2"), "no ghost")
        self.assertEqual(self.state("cold_trail"), 2, "hidden again: a new step")
        self.assertEqual(self.fn("universe_parked_quests")(), ["signal_2"])

    def test_was_moves_the_saved_state_to_the_new_key(self):
        self.evening(mode="New Game")
        quest_mark_complete(Agent.SHARED_ID, "signal_1")
        quest_set_key(Agent.SHARED_ID, "signal_2", "progress", 3)
        self.save()
        self.evening(self.renamed())
        self.assertEqual(self.state("cold_trail"), 1, "running, as signal_2 was")
        self.assertEqual(quest_get(Agent.SHARED_ID, "cold_trail").get("progress"), 3)
        self.assertIsNone(quest_get(Agent.SHARED_ID, "signal_2"))
        self.assertEqual(self.fn("universe_parked_quests")(), [], "moved, not parked")
        self.assertIn("'signal_2' is now 'cold_trail'", self.fn("universe_save_report")("Continue"))
        data = self.fn("universe_load")()
        self.assertEqual(quest_states(data["shared_quests"])["cold_trail"], (1, 3))
        self.assertNotIn("signal_2", data["shared_quests"])

    def test_was_is_spent_once_and_harmless_afterwards(self):
        self.evening(mode="New Game")
        quest_mark_complete(Agent.SHARED_ID, "signal_1")
        self.save()
        self.evening(self.renamed())
        quest_mark_complete(Agent.SHARED_ID, "cold_trail")
        self.save()
        self.evening(self.renamed())                       # the line is still in the file
        self.assertEqual(self.state("cold_trail"), 99)
        self.assertNotIn("is now", self.fn("universe_save_report")("Continue"))

    def test_was_reaches_a_step_that_had_been_parked(self):
        """Renamed with no `Was:` one evening, and the line added the next."""
        self.evening(mode="New Game")
        quest_mark_complete(Agent.SHARED_ID, "signal_1")
        self.save()
        self.evening(self.renamed(was=False))
        self.assertEqual(self.fn("universe_parked_quests")(), ["signal_2"])
        self.assertEqual(self.state("cold_trail"), 2, "fresh and hidden, for one evening")
        self.evening(self.renamed())
        self.assertEqual(self.state("cold_trail"), 1, "running, as signal_2 was left")
        self.assertEqual(self.fn("universe_parked_quests")(), [])

    def test_was_does_not_overrule_a_step_the_crew_has_started_since(self):
        self.evening(mode="New Game")
        quest_mark_complete(Agent.SHARED_ID, "signal_1")
        self.save()
        self.evening(self.renamed(was=False))
        quest_set_key(Agent.SHARED_ID, "cold_trail", "state", 99)   # done under the new key
        self.save()
        self.evening(self.renamed())
        self.assertEqual(self.state("cold_trail"), 99)
        self.assertEqual(self.fn("universe_parked_quests")(), ["signal_2"])


class StoryShapes(Evenings):
    """Renames inside an arc, a start trigger that had fired, a clock, an `Action:`."""

    file = SHAPES

    def test_a_renamed_arc_takes_its_steps_with_it(self):
        self.evening(mode="New Game")
        quest_on_signal("one_done")
        self.assertEqual([self.state(k) for k in ("arc/one", "arc/two")], [99, 1])
        self.save()
        text = with_field(self.file.replace("(arc)", "(saga)").replace("reveal arc/two",
                                                                         "reveal saga/two"),
                          "saga", "Was: arc")
        self.evening(text)
        self.assertEqual([self.state(k) for k in ("saga", "saga/one", "saga/two")], [1, 99, 1])
        self.assertIsNone(quest_get(Agent.SHARED_ID, "arc"))
        self.assertEqual(self.fn("universe_parked_quests")(), [])

    def test_a_renamed_step_inside_an_arc(self):
        self.evening(mode="New Game")
        quest_on_signal("one_done")
        self.save()
        text = with_field(self.file.replace("(two)", "(second)").replace(
            "reveal arc/two", "reveal arc/second"), "second", "Was: two")
        self.evening(text)
        self.assertEqual(self.state("arc/second"), 1, "`Was: two` is the sibling it was")
        self.assertEqual(self.fn("universe_parked_quests")(), [])

    def test_a_deleted_arc_parks_its_steps_too(self):
        self.evening(mode="New Game")
        quest_on_signal("one_done")
        self.save()
        text = without_record(without_record(without_record(self.file, "two"), "one"), "arc")
        self.evening(text)
        self.assertEqual(self.fn("universe_parked_quests")(), ["arc", "arc/one", "arc/two"])
        self.evening()
        self.assertEqual([self.state(k) for k in ("arc", "arc/one", "arc/two")], [1, 99, 1])

    # -- gap 9: a start trigger that had fired -------------------------------------------
    def test_GAP_9_a_step_that_had_started_is_not_armed_again(self):
        self.evening(mode="New Game")
        self.assertIn("armed_trigger", quest_get_data(Agent.SHARED_ID, "alarm"))
        quest_on_signal("alarm_raised")
        self.assertNotIn("armed_trigger", quest_get_data(Agent.SHARED_ID, "alarm"))
        data = self.save()
        self.assertTrue(data["shared_quests"]["alarm"].get("started"))
        self.evening()
        self.assertNotIn("armed_trigger", quest_get_data(Agent.SHARED_ID, "alarm"),
                         "it came back waiting for a signal that was sent last evening")
        quest_on_signal("alarm_cleared")
        self.assertEqual(self.state("alarm"), 99)

    def test_a_step_still_waiting_to_start_still_waits(self):
        self.evening(mode="New Game")
        data = self.save()
        self.assertNotIn("started", data["shared_quests"]["alarm"])
        self.evening()
        self.assertIn("armed_trigger", quest_get_data(Agent.SHARED_ID, "alarm"))

    def test_an_older_whole_record_says_it_had_started_by_its_data(self):
        """Saves written before story steps were slim hold the step's data, and a
        running step whose data has no `armed_trigger` had started."""
        self.evening(mode="New Game")
        quest_on_signal("alarm_raised")
        live = quest_get(Agent.SHARED_ID, "alarm")
        whole = {"display_text": "The Alarm", "description": "", "state": 1,
                 "data": copy.deepcopy(live.get("data")), "progress": 0, "children": {}}
        data = self.save()
        data["shared_quests"]["alarm"] = whole
        self.fn("universe_save_state")(data)
        self.evening()
        self.assertNotIn("armed_trigger", quest_get_data(Agent.SHARED_ID, "alarm"))

    # -- gap 9: clocks -------------------------------------------------------------------
    def test_GAP_9_a_running_clock_keeps_its_remaining_time(self):
        self.evening(mode="New Game")
        quest_tick_fail_after()                      # the driver starts the clock
        self.seconds(25)
        data = self.save()
        self.assertEqual(data["shared_quests"]["countdown"]["clocks"], {"fail": 35})
        self.evening()
        quest_tick_fail_after()
        self.assertEqual(get_time_remaining(Agent.SHARED_ID, "qfail:countdown"), 35,
                         "it came back with a full 60")
        self.seconds(36)
        quest_tick_fail_after()
        self.assertEqual(self.state("countdown"), 98)

    def test_the_save_is_kept_current_while_a_clock_runs(self):
        self.evening(mode="New Game")
        quest_tick_fail_after()
        self.save()
        self.seconds(10)
        self.assertFalse(self.fn("universe_save_flush")(), "not yet")
        self.seconds(25)
        self.assertTrue(self.fn("universe_save_flush")(), "nobody asked; the clock did")
        left = self.fn("universe_load")()["shared_quests"]["countdown"]["clocks"]["fail"]
        self.assertEqual(left, 25)

    def test_with_no_clock_running_nothing_is_written_unasked(self):
        self.evening(mode="New Game")
        quest_set_key(Agent.SHARED_ID, "countdown", "state", 99)
        self.save()
        self.seconds(120)
        self.assertFalse(self.fn("universe_save_flush")())

    def test_a_finished_steps_clock_is_not_saved(self):
        self.evening(mode="New Game")
        quest_tick_fail_after()
        quest_on_signal("reached_port")
        data = self.save()
        self.assertNotIn("clocks", data["shared_quests"]["countdown"])

    # -- gap 16: an at-once step's Action: -----------------------------------------------
    def test_GAP_16_the_action_of_a_step_the_save_knows_does_not_run_again(self):
        self.evening(mode="New Game")
        self.assertEqual(quest_actions_owed(), 1, "a new game owes the greeting its block")
        quest_tick_fail_after()                      # ...and the first tick runs it
        self.assertEqual(quest_actions_owed(), 0)
        quest_on_signal("greeted")
        self.save()
        self.evening()
        self.assertEqual(self.state("greeting"), 99)
        self.assertEqual(quest_actions_owed(), 0,
                         "granted running again on Continue, it owed its block again")

    def test_a_step_new_to_the_file_still_gets_its_action(self):
        """A step the save has never seen is starting for the first time tonight."""
        self.evening(SHAPES.replace("Action:\n  - yard becomes open\n", ""), mode="New Game")
        self.save()
        self.evening()
        self.assertEqual(quest_actions_owed(), 0)
        text = SHAPES + ("\n### [The Farewell](farewell)\n---\nScope: shared\nState: active\n"
                         "Done when: signal bye\nAction:\n  - yard becomes shut\n---\n")
        self.evening(text)
        self.assertEqual(quest_actions_owed(), 1)

    # -- Then: learn on a step, through the save -----------------------------------------
    def test_a_fact_a_step_taught_is_still_known_after_continue(self):
        self.evening(mode="New Game")
        quest_on_signal("greeted")
        self.assertEqual(boarding.boarding_facts(""), ["the yard is open"])
        self.assertTrue(self.fn("universe_save_flush")(), "the route asked; a fact also asks")
        self.evening()
        self.assertEqual(boarding.boarding_facts(""), ["the yard is open"])


RUIN = """# [Mission](mission)

## [Relics](relics)

### [The Hollow](hollow)
---
Loc: 0, 0, 20000
Walls: none
Debris: 0
---

### [The Mouth](mouth)
---
Relic: hollow
Chamber: 0, 0, 0, 900
---

### [the way in](hollow_door)
---
Relic: hollow
Point: -600, 0, 0
Roles: entrance
---

### [The Seized Hatch](nave_hatch)
---
Relic: hollow
Barrier: 300, 0, 0, 200
---
"""


class LibraryState(Evenings):
    """`state`: what the LIBRARY keeps - campaign facts, a ruin's ledger - written by
    its owners through the provider hook and handed back before anything is built."""

    file = story_file()

    def build_the_ruin(self):
        relics.relics_load("ruin.amd", content=RUIN)
        self.assertIsNotNone(relics.relic_spawn("hollow", atmosphere=False, marker=False))

    def test_a_campaign_fact_is_saved_without_anybody_asking(self):
        self.evening(mode="New Game")
        self.assertFalse(self.fn("universe_save_flush")(), "nothing to write")
        boarding.boarding_learn("manifest", place="")
        self.assertFalse(self.fn("universe_save_pending")())
        self.assertTrue(self.fn("universe_save_flush")(), "the library said something changed")
        self.assertEqual(self.fn("universe_load")()["state"],
                         {"boarding_facts": {"": ["manifest"]}})

    def test_it_is_known_again_after_continue(self):
        self.evening(mode="New Game")
        boarding.boarding_learn("manifest", place="")
        self.save()
        self.evening()
        self.assertEqual(boarding.boarding_facts(""), ["manifest"])
        self.assertEqual(boarding.boarding_learned_guard("learned manifest"), 1)

    def test_a_new_game_knows_nothing_and_the_file_says_so(self):
        self.evening(mode="New Game")
        boarding.boarding_learn("manifest", place="")
        self.save()
        self.evening(mode="New Game")
        self.assertEqual(boarding.boarding_facts(""), [])
        self.assertNotIn("state", self.fn("universe_load")())

    def test_a_ruin_is_as_it_was_left_after_continue_and_says_nothing(self):
        self.evening(mode="New Game")
        self.build_the_ruin()
        self.assertTrue(relics.relic_open_barrier("hollow", "nave_hatch"))
        self.assertTrue(self.fn("universe_save_flush")())
        self.assertEqual(self.fn("universe_load")()["state"]["relics"], {
            "ruins": {"hollow": {"opened": ["nave_hatch"]}}, "sent": ["nave_hatch_opened"]})
        self.evening()
        heard = []
        from sbs_utils.procedural.signal import signal_observe, signal_unobserve
        watch = lambda name, data=None: heard.append(name)
        signal_observe(watch)
        self.addCleanup(signal_unobserve, watch)
        self.build_the_ruin()                        # the crew flies back to it
        from sbs_utils.procedural import rails
        self.assertEqual(rails.rail_barriers("hollow", shut_only=True), [])
        self.assertNotIn("quest_signal", heard)
        self.assertNotIn("rail_opened", heard)

    def test_the_state_is_handed_back_before_anything_is_built(self):
        """universe_save_begin is where it happens - the first system, and any ruin in
        it, is built straight after."""
        self.evening(mode="New Game")
        self.build_the_ruin()
        relics.relic_open_barrier("hollow", "nave_hatch")
        self.save()
        self.launch()
        self.assertEqual(relics.relic_ledger(), {})
        self.begin("Continue")
        self.assertEqual(relics.relic_ledger(), {"hollow": {"opened": ["nave_hatch"]}})

    def test_nothing_is_written_over_the_state_before_the_save_is_opened(self):
        self.evening(mode="New Game")
        boarding.boarding_learn("manifest", place="")
        self.save()
        self.launch()                                # ...and a save before universe_save_begin
        self.ship("Artemis")
        self.fn("universe_save_ready")()
        self.fn("universe_save_players")()
        self.assertEqual(self.fn("universe_load")()["state"],
                         {"boarding_facts": {"": ["manifest"]}})

    def test_the_universes_own_guard_resolver_answers_learned(self):
        """`_ou_metric` is installed as the guard resolver as universe_dialogue.py
        loads. It read every name it did not own as a reputation pole - 0."""
        story = MastStory()
        story.basedir = OU_CORE
        self.assertEqual(story.compile("import universe_dialogue.py\n", "dlg", story), [])
        metric = self.fn("universe_dialogue_scenes").__globals__["_ou_metric"]
        live = self.evening(mode="New Game")
        ship = live["Artemis"].id
        self.assertEqual(metric("learned manifest", ship, None), 0)
        self.assertEqual(metric("learned", ship, None), 0)
        boarding.boarding_learn("Manifest", place="")
        self.assertEqual(metric("learned manifest", ship, None), 1)
        self.assertEqual(metric("learned", ship, None), 1)
        self.assertEqual(metric("credits", ship, None), 500, "its own words still answer")


class Campaign(Evenings):
    file = story_file()

    def test_the_storys_own_copy_of_a_shared_beats_standing_is_kept(self):
        """A shared beat pays every ship flying (kept per ship) AND the story agent,
        whose copy is what a message reply's `if standing` reads. That copy was lost."""
        self.evening(mode="New Game")
        self.assertNotIn("shared_reputation", self.save(), "nothing earned, nothing written")
        set_inventory_value(Agent.SHARED_ID, "reputation", {"iron": {"honesty": 20}})
        self.assertEqual(self.save()["shared_reputation"], {"iron": {"honesty": 20}})
        self.evening()
        self.assertEqual(get_inventory_value(Agent.SHARED_ID, "reputation"),
                         {"iron": {"honesty": 20}})
        self.evening(mode="New Game")
        self.assertFalse(get_inventory_value(Agent.SHARED_ID, "reputation", None))

    def test_GAP_14_a_won_campaign_is_remembered(self):
        self.evening(mode="New Game")
        self.assertEqual(self.fn("universe_campaign_ended")(), "")
        self.fn("universe_campaign_end")("won", "Answer the Signal")
        self.assertTrue(self.fn("universe_save_pending")())
        self.assertTrue(self.fn("universe_save_flush")())
        self.assertEqual(self.fn("universe_load")()["campaign"],
                         {"ended": "won", "title": "Answer the Signal"})
        self.evening()
        self.assertEqual(self.fn("universe_campaign_ended")(), "won")
        self.assertEqual(self.fn("universe_campaign_title")(), "Answer the Signal")
        self.save()
        self.evening()                               # ...and the evening after that
        self.assertEqual(self.fn("universe_campaign_ended")(), "won")

    def test_a_new_game_is_a_campaign_nobody_has_won(self):
        self.evening(mode="New Game")
        self.fn("universe_campaign_end")("won", "Answer the Signal")
        self.save()
        self.evening(mode="New Game")
        self.assertEqual(self.fn("universe_campaign_ended")(), "")
        self.assertNotIn("campaign", self.fn("universe_load")())

    def test_the_card_is_one_card_on_a_continue_of_a_won_campaign(self):
        with open(os.path.join(OU_CORE, "universe.mast"), encoding="utf-8") as f:
            text = f.read()
        begin = text.index("=== universe_map_begin")
        end = text.index("\n=== ", begin + 10)
        body = text[begin:end]
        self.assertIn('if START_MODE == "Continue" and universe_campaign_ended() == "won":\n'
                      "        task_schedule(universe_campaign_card)", body)
        self.assertEqual(text.count("task_schedule(universe_campaign_card)"), 1)
        card = text[text.index("=== universe_campaign_card"):]
        card = card[:card.index("\n=== ", 10)]
        self.assertEqual(card.count("universe_info_card("), 2, "one of two is sent")
        self.assertIn('"Campaign won"', card)
        # ...and the route that ends a campaign is what remembers it. A server route.
        route = text[text.index("//shared/signal/quest_succeeded if UNIVERSE_ACTIVE"):]
        route = route[:route.index("\n\n\n")]
        self.assertIn('universe_campaign_end("won"', route)
        self.assertIn('universe_campaign_end("lost"', route)


class OwnCell(Evenings):
    file = story_file()

    def test_GAP_13_each_ship_is_put_back_in_its_own_system(self):
        live = self.evening(mode="New Game", ships=("Artemis", "Intrepid"))
        self.fn("ship_set_cell")(live["Artemis"].id, 1, -1)
        self.fn("ship_set_cell")(live["Intrepid"].id, 3, -2)
        self.fn("universe_save")(7, 1, -1, {})       # the last jumper was Artemis
        self.save()
        live = self.evening(ships=("Artemis", "Intrepid"))
        # universe_map_begin has put both in the save's one `current_system`.
        for ship in live.values():
            self.fn("ship_set_cell")(ship.id, 1, -1)
        self.assertEqual(self.fn("universe_saved_cells")(), [[live["Intrepid"].id, 3, -2]])
        # ...and once it has moved her there, there is nothing left to do.
        self.fn("ship_set_cell")(live["Intrepid"].id, 3, -2)
        self.assertEqual(self.fn("universe_saved_cells")(), [])

    def test_a_record_with_no_cell_stays_where_the_save_says(self):
        self.install("v1_default.yaml")              # version 1: no cell in a record
        self.evening()
        self.assertEqual(self.fn("universe_saved_cells")(), [])

    def test_a_new_game_moves_nobody(self):
        live = self.evening(mode="New Game")
        self.fn("ship_set_cell")(live["Artemis"].id, 3, -2)
        self.save()
        self.evening(mode="New Game")
        self.assertEqual(self.fn("universe_saved_cells")(), [])

    def test_the_start_sequence_moves_them_and_releases_ruins_before_a_teardown(self):
        with open(os.path.join(OU_CORE, "universe.mast"), encoding="utf-8") as f:
            text = f.read()
        begin = text.index("=== universe_map_begin")
        order = [text.index(call, begin) for call in (
            "\n    universe_load_players(", "\n    for _sc in universe_saved_cells():",
            "\n    universe_save_ready()")]
        self.assertEqual(order, sorted(order))
        # A ruin lets go of its objects BEFORE they are deleted, in both teardowns, so
        # that a deleted barrier can never be read as one that was shot open.
        for start in ("=== universe_map_begin", "=== universe_jump_to"):
            body = text[text.index(start):]
            release = body.index("universe_relic_release_cell(")
            clear = body.index("universe_clear_cell(")
            self.assertLess(release, clear, start)


class Fixtures(Evenings):
    """Saves written by THIS build, by playing sandbox copies headless."""

    def test_the_version_2_story_fixture_is_slim_and_comes_back_whole(self):
        before_bytes = self.install("v2_story.yaml")
        before = fs.load_yaml_data(self.path)
        self.assertEqual(before["save_version"], 2)
        for key, rec in before["shared_quests"].items():
            if key != "waypoints":
                self.assertTrue(rec.get("authored"), key)
                self.assertNotIn("description", rec, key)
        self.evening(story_file())
        after = self.fn("universe_load")()
        self.assertEqual(quest_states(after["shared_quests"]),
                         quest_states(before["shared_quests"]))
        self.assertEqual(after.get("campaign"), before.get("campaign"))
        self.assertEqual(self.files(), ["universe_save_round_trip_1.yaml"],
                         "a version-2 file is not backed up or upgraded")
        self.assertTrue(before_bytes)

    def test_the_version_2_ruin_fixture_hands_its_state_back(self):
        self.install("v2_ruin.yaml")
        before = fs.load_yaml_data(self.path)
        self.assertIn("relics", before["state"])
        self.assertIn("boarding_facts", before["state"])
        self.launch()
        self.ship("Artemis")
        saved = self.begin("Continue")
        self.assertEqual(persistence.persist_providers_snapshot(), before["state"])
        self.finish("Continue", saved)
        after = self.fn("universe_load")()
        self.assertEqual(after["state"], before["state"])
        self.assertEqual(quest_states(after["shared_quests"]),
                         quest_states(before["shared_quests"]))


if __name__ == "__main__":
    unittest.main()
